import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { basename, join } from 'path'
import { userHomeDir } from '@main/platform.js'

type PtyEnv = Record<string, string | undefined>

export interface PtyShellIntegrationOptions {
  enabled: boolean
  file: string
  args: string[]
  env: PtyEnv
  userDataDir: string
  platform?: NodeJS.Platform
}

export interface PreparedPtyCommand {
  file: string
  args: string[]
  env: Record<string, string>
}

const ZSHENV = [
  '# Generated by Mim. Do not edit.',
  '# This proxy sources the user\'s real .zshenv, then forces zsh to continue',
  '# startup from Mim\'s generated ZDOTDIR so .zshrc below is not skipped.',
  'if [[ -n "${MIM_ORIGINAL_ZDOTDIR:-}" && -r "${MIM_ORIGINAL_ZDOTDIR}/.zshenv" ]]; then',
  '  source "${MIM_ORIGINAL_ZDOTDIR}/.zshenv"',
  'fi',
  '',
  'if [[ -n "${ZDOTDIR:-}" && "${ZDOTDIR}" != "${MIM_ZSH_INTEGRATION_DIR:-}" ]]; then',
  '  export MIM_USER_ZDOTDIR_AFTER_ZSHENV="${ZDOTDIR}"',
  'elif [[ -z "${MIM_USER_ZDOTDIR_AFTER_ZSHENV:-}" && -n "${MIM_ORIGINAL_ZDOTDIR:-}" ]]; then',
  '  export MIM_USER_ZDOTDIR_AFTER_ZSHENV="${MIM_ORIGINAL_ZDOTDIR}"',
  'fi',
  '',
  'if [[ -n "${MIM_ZSH_INTEGRATION_DIR:-}" ]]; then',
  '  export ZDOTDIR="${MIM_ZSH_INTEGRATION_DIR}"',
  'fi',
  '',
].join('\n')

const ZSHRC = [
  '# Generated by Mim. Do not edit.',
  '# Source the user\'s real .zshrc first, then add terminal bindings that make',
  '# xterm.js keyboard sequences work in both emacs and vi insert keymaps.',
  'if [[ -n "${MIM_USER_ZDOTDIR_AFTER_ZSHENV:-}" \\',
  '      && "${MIM_USER_ZDOTDIR_AFTER_ZSHENV}" != "${MIM_ZSH_INTEGRATION_DIR:-}" \\',
  '      && -r "${MIM_USER_ZDOTDIR_AFTER_ZSHENV}/.zshrc" ]]; then',
  '  source "${MIM_USER_ZDOTDIR_AFTER_ZSHENV}/.zshrc"',
  'elif [[ -n "${MIM_ORIGINAL_ZDOTDIR:-}" \\',
  '        && "${MIM_ORIGINAL_ZDOTDIR}" != "${MIM_ZSH_INTEGRATION_DIR:-}" \\',
  '        && -r "${MIM_ORIGINAL_ZDOTDIR}/.zshrc" ]]; then',
  '  source "${MIM_ORIGINAL_ZDOTDIR}/.zshrc"',
  'fi',
  '',
  'if [[ -o interactive ]]; then',
  '  for keymap in emacs viins; do',
  '    # xterm modified Option/Alt arrows.',
  '    bindkey -M "${keymap}" $\'\\e[1;3D\' backward-word 2>/dev/null',
  '    bindkey -M "${keymap}" $\'\\e[1;3C\' forward-word 2>/dev/null',
  '    bindkey -M "${keymap}" $\'\\e[1;4D\' backward-word 2>/dev/null',
  '    bindkey -M "${keymap}" $\'\\e[1;4C\' forward-word 2>/dev/null',
  '    bindkey -M "${keymap}" $\'\\e[1;2D\' backward-char 2>/dev/null',
  '    bindkey -M "${keymap}" $\'\\e[1;2C\' forward-char 2>/dev/null',
  '',
  '    # Home/End forms seen across xterm-compatible terminals.',
  '    bindkey -M "${keymap}" $\'\\e[H\' beginning-of-line 2>/dev/null',
  '    bindkey -M "${keymap}" $\'\\e[F\' end-of-line 2>/dev/null',
  '    bindkey -M "${keymap}" $\'\\eOH\' beginning-of-line 2>/dev/null',
  '    bindkey -M "${keymap}" $\'\\eOF\' end-of-line 2>/dev/null',
  '    bindkey -M "${keymap}" $\'\\e[1~\' beginning-of-line 2>/dev/null',
  '    bindkey -M "${keymap}" $\'\\e[4~\' end-of-line 2>/dev/null',
  '',
  '    # Renderer fallbacks for macOS Cmd+Arrow and Option+Backspace.',
  '    bindkey -M "${keymap}" \'^A\' beginning-of-line 2>/dev/null',
  '    bindkey -M "${keymap}" \'^E\' end-of-line 2>/dev/null',
  '    bindkey -M "${keymap}" \'^W\' backward-kill-word 2>/dev/null',
  '  done',
  'fi',
  '',
  'if [[ -n "${MIM_USER_ZDOTDIR_AFTER_ZSHENV:-}" \\',
  '      && "${MIM_USER_ZDOTDIR_AFTER_ZSHENV}" != "${MIM_ZSH_INTEGRATION_DIR:-}" ]]; then',
  '  export ZDOTDIR="${MIM_USER_ZDOTDIR_AFTER_ZSHENV}"',
  'fi',
  '',
].join('\n')

export function zshIntegrationDir(userDataDir: string): string {
  return join(userDataDir, 'shell', 'zsh')
}

export function preparePtyShellIntegration(options: PtyShellIntegrationOptions): PreparedPtyCommand {
  const env = compactEnv(options.env)
  if (!options.enabled || !isScratchZsh(options.file, options.args, options.platform)) {
    return { file: options.file, args: options.args, env }
  }

  const integrationDir = zshIntegrationDir(options.userDataDir)
  ensureZshIntegrationFiles(integrationDir)
  const originalZdotdir = env.ZDOTDIR || userHomeDir(env)

  return {
    file: options.file,
    args: options.args,
    env: {
      ...env,
      ZDOTDIR: integrationDir,
      MIM_ORIGINAL_ZDOTDIR: originalZdotdir,
      MIM_USER_ZDOTDIR_AFTER_ZSHENV: originalZdotdir,
      MIM_ZSH_INTEGRATION_DIR: integrationDir,
      MIM_SHELL_INTEGRATION: 'zsh',
    },
  }
}

function isScratchZsh(file: string, args: string[], platform = process.platform): boolean {
  if (platform === 'win32' || args.length > 0) return false
  const name = basename(file)
  return name === 'zsh' || name === '-zsh'
}

function ensureZshIntegrationFiles(dir: string): void {
  mkdirSync(dir, { recursive: true })
  writeIfChanged(join(dir, '.zshenv'), ZSHENV)
  writeIfChanged(join(dir, '.zshrc'), ZSHRC)
}

function writeIfChanged(path: string, content: string): void {
  if (existsSync(path) && readFileSync(path, 'utf8') === content) return
  writeFileSync(path, content, { encoding: 'utf8', mode: 0o644 })
}

function compactEnv(env: PtyEnv): Record<string, string> {
  const next: Record<string, string> = {}
  for (const [key, value] of Object.entries(env)) {
    if (typeof value === 'string') next[key] = value
  }
  return next
}
